# Generated by Django 4.2.1 on 2023-05-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu_item",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
