# Generated by Django 4.2.1 on 2023-05-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_menu_item_image"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ord_date_created", models.DateTimeField(auto_now_add=True)),
                ("ord_date_deliverd", models.DateTimeField(auto_now_add=True)),
                ("ord_items", models.ManyToManyField(to="menu.menu_item")),
                (
                    "table_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="table",
                        to="order.table",
                    ),
                ),
            ],
        ),
    ]
