# Generated by Django 4.2.1 on 2023-05-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_deliverd",
            field=models.BooleanField(default=False),
        ),
    ]
