# Generated by Django 4.2.1 on 2023-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_is_deliverd"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_taken",
            field=models.BooleanField(default=False),
        ),
    ]
